const { v4: uuidv4 } = require('uuid');

exports.seed = async function (knex) {
  const NO_BRANCH_ID = '00000000-0000-4000-8000-000000000000';
  const superAdminId = '00000000-0000-4000-8000-000000000000';

  await knex('branches').del();

  const branches = [
    {
      id: NO_BRANCH_ID,
      name_uz: 'Texnik filial',
      name_ru: 'Технический филиал',
      name_en: 'Technical Branch',
      address_uz: 'Aniqlanmagan',
      address_ru: 'Не указано',
      address_en: 'Unknown',
      lat: null,
      long: null,
      support_phone: null,
      work_start_time: null,
      work_end_time: null,
      bg_color: '#cccccc',
      color: '#000000',
      status: 'Open',
      is_active: true,
      is_protected: true,
      created_by: superAdminId,
      sort: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    // Realistic branch data
    {
      id: uuidv4(),
      name_uz: 'Toshkent Markaziy Filial',
      name_ru: 'Ташкент Центральный Филиал',
      name_en: 'Tashkent Central Branch',
      address_uz: 'Amir Temur ko\'chasi, 123-uy, Toshkent',
      address_ru: 'Улица Амира Темура, дом 123, Ташкент',
      address_en: 'Amir Temur Street, Building 123, Tashkent',
      lat: 41.3111,
      long: 69.2797,
      support_phone: '+998901234567',
      work_start_time: '09:00',
      work_end_time: '18:00',
      bg_color: '#4CAF50',
      color: '#FFFFFF',
      status: 'Open',
      is_active: true,
      is_protected: false,
      created_by: superAdminId,
      sort: 2,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: uuidv4(),
      name_uz: 'Chilonzor Filial',
      name_ru: 'Чилонзар Филиал',
      name_en: 'Chilonzor Branch',
      address_uz: 'Chilonzor ko\'chasi, 45-uy, Toshkent',
      address_ru: 'Улица Чилонзар, дом 45, Ташкент',
      address_en: 'Chilonzor Street, Building 45, Toshkent',
      lat: 41.2800,
      long: 69.2042,
      support_phone: '+998901234568',
      work_start_time: '09:00',
      work_end_time: '19:00',
      bg_color: '#2196F3',
      color: '#FFFFFF',
      status: 'Open',
      is_active: true,
      is_protected: false,
      created_by: superAdminId,
      sort: 3,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: uuidv4(),
      name_uz: 'Yunusobod Filial',
      name_ru: 'Юнусабад Филиал',
      name_en: 'Yunusobod Branch',
      address_uz: 'Yunusobod ko\'chasi, 78-uy, Toshkent',
      address_ru: 'Улица Юнусабад, дом 78, Ташкент',
      address_en: 'Yunusobod Street, Building 78, Tashkent',
      lat: 41.3500,
      long: 69.2800,
      support_phone: '+998901234569',
      work_start_time: '08:00',
      work_end_time: '18:00',
      bg_color: '#FF9800',
      color: '#FFFFFF',
      status: 'Open',
      is_active: true,
      is_protected: false,
      created_by: superAdminId,
      sort: 4,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: uuidv4(),
      name_uz: 'Samarqand Filial',
      name_ru: 'Самарканд Филиал',
      name_en: 'Samarkand Branch',
      address_uz: 'Registon ko\'chasi, 12-uy, Samarqand',
      address_ru: 'Улица Регистан, дом 12, Самарканд',
      address_en: 'Registon Street, Building 12, Samarkand',
      lat: 39.6542,
      long: 66.9597,
      support_phone: '+998901234570',
      work_start_time: '09:00',
      work_end_time: '18:00',
      bg_color: '#9C27B0',
      color: '#FFFFFF',
      status: 'Open',
      is_active: true,
      is_protected: false,
      created_by: superAdminId,
      sort: 5,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: uuidv4(),
      name_uz: 'Buxoro Filial',
      name_ru: 'Бухара Филиал',
      name_en: 'Bukhara Branch',
      address_uz: 'Buxoro ko\'chasi, 34-uy, Buxoro',
      address_ru: 'Улица Бухара, дом 34, Бухара',
      address_en: 'Bukhara Street, Building 34, Bukhara',
      lat: 39.7756,
      long: 64.4286,
      support_phone: '+998901234571',
      work_start_time: '09:00',
      work_end_time: '18:00',
      bg_color: '#F44336',
      color: '#FFFFFF',
      status: 'Open',
      is_active: true,
      is_protected: false,
      created_by: superAdminId,
      sort: 6,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    ...Array.from({ length: 14 }).map((_, i) => {
      const branchNames = [
        { uz: 'Navoiy Filial', ru: 'Навои Филиал', en: 'Navoi Branch' },
        { uz: 'Andijon Filial', ru: 'Андижан Филиал', en: 'Andijan Branch' },
        { uz: 'Farg\'ona Filial', ru: 'Фергана Филиал', en: 'Fergana Branch' },
        { uz: 'Namangan Filial', ru: 'Наманган Филиал', en: 'Namangan Branch' },
        { uz: 'Qarshi Filial', ru: 'Карши Филиал', en: 'Karshi Branch' },
        { uz: 'Termiz Filial', ru: 'Термез Филиал', en: 'Termez Branch' },
        { uz: 'Jizzax Filial', ru: 'Джизак Филиал', en: 'Jizzakh Branch' },
        { uz: 'Guliston Filial', ru: 'Гулистан Филиал', en: 'Gulistan Branch' },
        { uz: 'Urganch Filial', ru: 'Ургенч Филиал', en: 'Urgench Branch' },
        { uz: 'Nukus Filial', ru: 'Нукус Филиал', en: 'Nukus Branch' },
        { uz: 'Angren Filial', ru: 'Ангрен Филиал', en: 'Angren Branch' },
        { uz: 'Bekobod Filial', ru: 'Бекабад Филиал', en: 'Bekabad Branch' },
        { uz: 'Olmaliq Filial', ru: 'Олмалик Филиал', en: 'Almalyk Branch' },
        { uz: 'Chirchiq Filial', ru: 'Чирчик Филиал', en: 'Chirchik Branch' },
      ];
      
      const branch = branchNames[i % branchNames.length];
      const colors = [
        { bg: '#E91E63', text: '#FFFFFF' },
        { bg: '#00BCD4', text: '#FFFFFF' },
        { bg: '#8BC34A', text: '#FFFFFF' },
        { bg: '#FFC107', text: '#000000' },
        { bg: '#795548', text: '#FFFFFF' },
        { bg: '#607D8B', text: '#FFFFFF' },
        { bg: '#3F51B5', text: '#FFFFFF' },
        { bg: '#009688', text: '#FFFFFF' },
        { bg: '#CDDC39', text: '#000000' },
        { bg: '#FF5722', text: '#FFFFFF' },
        { bg: '#9E9E9E', text: '#FFFFFF' },
        { bg: '#673AB7', text: '#FFFFFF' },
        { bg: '#00E676', text: '#000000' },
        { bg: '#FF1744', text: '#FFFFFF' },
      ];
      
      const color = colors[i % colors.length];
      
      return {
        id: uuidv4(),
        name_uz: branch.uz,
        name_ru: branch.ru,
        name_en: branch.en,
        address_uz: `${branch.uz.replace(' Filial', '')} ko'chasi, ${i + 10}-uy`,
        address_ru: `Улица ${branch.ru.replace(' Филиал', '')}, дом ${i + 10}`,
        address_en: `${branch.en.replace(' Branch', '')} Street, Building ${i + 10}`,
        lat: 41.0 + (i * 0.1),
        long: 69.0 + (i * 0.1),
        support_phone: `+99890${String(1234572 + i).slice(-7)}`,
        work_start_time: '09:00',
        work_end_time: '18:00',
        bg_color: color.bg,
        color: color.text,
        status: 'Open',
        is_active: true,
        is_protected: false,
        created_by: superAdminId,
        sort: i + 7,
        created_at: knex.fn.now(),
        updated_at: knex.fn.now(),
      };
    }),
  ];

  await knex('branches').insert(branches);
};
