exports.seed = async function (knex) {
  await knex('app_features').del();

  const appFeatures = [
    {
      id: '90000000-0000-0000-0000-000000000001',
      name_uz: 'Tamir buyurtmasi berish',
      name_ru: 'Подача заявки на ремонт',
      name_en: 'Submit Repair Request',
      description_uz: 'Foydalanuvchilar telefon ta\'mir buyurtmasi berishlari mumkin',
      description_ru: 'Пользователи могут подавать заявки на ремонт телефонов',
      description_en: 'Users can submit phone repair requests',
      icon: '🔧',
      is_active: true,
      sort: 1,
    },
    {
      id: '90000000-0000-0000-0000-000000000002',
      name_uz: 'Buyurtma holatini kuzatish',
      name_ru: 'Отслеживание статуса заказа',
      name_en: 'Track Order Status',
      description_uz: 'Buyurtma holatini real vaqtda kuzatib boring',
      description_ru: 'Отслеживайте статус заказа в реальном времени',
      description_en: 'Track your order status in real-time',
      icon: '📱',
      is_active: true,
      sort: 2,
    },
    {
      id: '90000000-0000-0000-0000-000000000003',
      name_uz: 'Onlayn to\'lov',
      name_ru: 'Онлайн оплата',
      name_en: 'Online Payment',
      description_uz: 'Click, Payme va boshqa to\'lov tizimlari orqali to\'lang',
      description_ru: 'Оплачивайте через Click, Payme и другие платежные системы',
      description_en: 'Pay through Click, Payme and other payment systems',
      icon: '💳',
      is_active: true,
      sort: 3,
    },
    {
      id: '90000000-0000-0000-0000-000000000004',
      name_uz: 'Yetkazib berish',
      name_ru: 'Доставка',
      name_en: 'Delivery Service',
      description_uz: 'Telefoningizni olib ketish va qaytarish xizmati',
      description_ru: 'Услуга забора и возврата телефона',
      description_en: 'Phone pickup and return service',
      icon: '🚚',
      is_active: true,
      sort: 4,
    },
    {
      id: '90000000-0000-0000-0000-000000000005',
      name_uz: 'Ijara telefoni',
      name_ru: 'Аренда телефона',
      name_en: 'Phone Rental',
      description_uz: 'Ta\'mir davomida vaqtincha telefon ijarasi',
      description_ru: 'Аренда временного телефона на время ремонта',
      description_en: 'Temporary phone rental during repair',
      icon: '📞',
      is_active: true,
      sort: 5,
    },
    {
      id: '90000000-0000-0000-0000-000000000006',
      name_uz: 'Push bildirishnomalar',
      name_ru: 'Push уведомления',
      name_en: 'Push Notifications',
      description_uz: 'Buyurtma haqida darhol xabar oling',
      description_ru: 'Получайте мгновенные уведомления о заказе',
      description_en: 'Get instant notifications about your order',
      icon: '🔔',
      is_active: true,
      sort: 6,
    },
    {
      id: '90000000-0000-0000-0000-000000000007',
      name_uz: 'Qo\'llab-quvvatlash xizmati',
      name_ru: 'Служба поддержки',
      name_en: 'Customer Support',
      description_uz: '24/7 mijozlarni qo\'llab-quvvatlash xizmati',
      description_ru: 'Круглосуточная служба поддержки клиентов',
      description_en: '24/7 customer support service',
      icon: '💬',
      is_active: true,
      sort: 7,
    },
    {
      id: '90000000-0000-0000-0000-000000000008',
      name_uz: 'Tamir tarixi',
      name_ru: 'История ремонтов',
      name_en: 'Repair History',
      description_uz: 'Barcha ta\'mir buyurtmalaringiz tarixi',
      description_ru: 'История всех ваших заявок на ремонт',
      description_en: 'History of all your repair orders',
      icon: '📋',
      is_active: true,
      sort: 8,
    },
    {
      id: '90000000-0000-0000-0000-000000000009',
      name_uz: 'Narxlarni hisoblash',
      name_ru: 'Калькулятор цен',
      name_en: 'Price Calculator',
      description_uz: 'Ta\'mir narxini oldindan hisoblang',
      description_ru: 'Предварительно рассчитайте стоимость ремонта',
      description_en: 'Pre-calculate repair costs',
      icon: '🧮',
      is_active: true,
      sort: 9,
    },
    {
      id: '90000000-0000-0000-0000-000000000010',
      name_uz: 'Filiallarni topish',
      name_ru: 'Поиск филиалов',
      name_en: 'Find Branches',
      description_uz: 'Eng yaqin filialimizni toping',
      description_ru: 'Найдите ближайший филиал',
      description_en: 'Find the nearest branch',
      icon: '📍',
      is_active: true,
      sort: 10,
    },
    {
      id: '90000000-0000-0000-0000-000000000011',
      name_uz: 'Chegirmalar va aksiyalar',
      name_ru: 'Скидки и акции',
      name_en: 'Discounts and Promotions',
      description_uz: 'Maxsus chegirmalar va aksiyalardan foydalaning',
      description_ru: 'Воспользуйтесь специальными скидками и акциями',
      description_en: 'Take advantage of special discounts and promotions',
      icon: '🎁',
      is_active: true,
      sort: 11,
    },
    {
      id: '90000000-0000-0000-0000-000000000012',
      name_uz: 'Kafolat xizmati',
      name_ru: 'Гарантийное обслуживание',
      name_en: 'Warranty Service',
      description_uz: 'Ta\'mir ishlari uchun kafolat berish',
      description_ru: 'Гарантия на ремонтные работы',
      description_en: 'Warranty on repair services',
      icon: '🛡️',
      is_active: true,
      sort: 12,
    },
    {
      id: '90000000-0000-0000-0000-000000000013',
      name_uz: 'Onlayn chat',
      name_ru: 'Онлайн чат',
      name_en: 'Online Chat',
      description_uz: 'Mutaxassislar bilan onlayn suhbatlashish',
      description_ru: 'Общение с экспертами в онлайн-чате',
      description_en: 'Chat with experts online',
      icon: '💬',
      is_active: true,
      sort: 13,
    },
    {
      id: '90000000-0000-0000-0000-000000000014',
      name_uz: 'Video diagnostika',
      name_ru: 'Видео диагностика',
      name_en: 'Video Diagnosis',
      description_uz: 'Video orqali telefon muammosini aniqlash',
      description_ru: 'Определение проблемы телефона через видео',
      description_en: 'Identify phone issues through video',
      icon: '📹',
      is_active: true,
      sort: 14,
    },
    {
      id: '90000000-0000-0000-0000-000000000015',
      name_uz: 'Qo\'ng\'iroq qaytarish',
      name_ru: 'Обратный звонок',
      name_en: 'Callback Request',
      description_uz: 'Mutaxassislardan qo\'ng\'iroq so\'rash',
      description_ru: 'Запрос обратного звонка от специалистов',
      description_en: 'Request callback from specialists',
      icon: '📞',
      is_active: true,
      sort: 15,
    },
    {
      id: '90000000-0000-0000-0000-000000000016',
      name_uz: 'Reyting va sharhlar',
      name_ru: 'Рейтинги и отзывы',
      name_en: 'Ratings and Reviews',
      description_uz: 'Xizmat sifatini baholash va sharh qoldirish',
      description_ru: 'Оценить качество обслуживания и оставить отзыв',
      description_en: 'Rate service quality and leave reviews',
      icon: '⭐',
      is_active: true,
      sort: 16,
    },
    {
      id: '90000000-0000-0000-0000-000000000017',
      name_uz: 'Loyiha kuzatish',
      name_ru: 'Отслеживание проекта',
      name_en: 'Project Tracking',
      description_uz: 'Ta\'mir jarayonini batafsil kuzatish',
      description_ru: 'Детальное отслеживание процесса ремонта',
      description_en: 'Detailed tracking of repair process',
      icon: '👁️',
      is_active: true,
      sort: 17,
    },
    {
      id: '90000000-0000-0000-0000-000000000018',
      name_uz: 'Hisob-kitob',
      name_ru: 'Счет',
      name_en: 'Account',
      description_uz: 'Shaxsiy hisob va sozlamalar',
      description_ru: 'Личный кабинет и настройки',
      description_en: 'Personal account and settings',
      icon: '👤',
      is_active: true,
      sort: 18,
    },
    {
      id: '90000000-0000-0000-0000-000000000019',
      name_uz: 'Qo\'llanma va yordam',
      name_ru: 'Руководство и помощь',
      name_en: 'Guide and Help',
      description_uz: 'Foydalanish bo\'yicha qo\'llanma va tez-tez beriladigan savollar',
      description_ru: 'Руководство по использованию и часто задаваемые вопросы',
      description_en: 'User guide and frequently asked questions',
      icon: '❓',
      is_active: true,
      sort: 19,
    },
    {
      id: '90000000-0000-0000-0000-000000000020',
      name_uz: 'Vaqt jadvali',
      name_ru: 'Расписание',
      name_en: 'Schedule',
      description_uz: 'Filiallar ish vaqtini ko\'rish va uchrashuv belgilash',
      description_ru: 'Просмотр рабочего времени филиалов и запись на прием',
      description_en: 'View branch hours and schedule appointments',
      icon: '📅',
      is_active: true,
      sort: 20,
    },
  ];

  for (const feature of appFeatures) {
    await knex('app_features').insert({
      id: feature.id,
      name_uz: feature.name_uz,
      name_ru: feature.name_ru,
      name_en: feature.name_en,
      description_uz: feature.description_uz,
      description_ru: feature.description_ru,
      description_en: feature.description_en,
      icon: feature.icon,
      is_active: feature.is_active,
      sort: feature.sort,
      status: 'Open',
      created_by: '00000000-0000-0000-0000-000000000001', // Super admin
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    });
  }
};