exports.seed = async function (knex) {
  await knex('app_features').del();

  const appFeatures = [
    {
      id: '90000000-0000-0000-0000-000000000001',
      name_uz: 'Tamir buyurtmasi berish',
      name_ru: 'Подача заявки на ремонт',
      name_en: 'Submit Repair Request',
      description_uz: 'Foydalanuvchilar telefon ta\'mir buyurtmasi berishlari mumkin',
      description_ru: 'Пользователи могут подавать заявки на ремонт телефонов',
      description_en: 'Users can submit phone repair requests',
      icon: '🔧',
      is_active: true,
      sort: 1,
    },
    {
      id: '90000000-0000-0000-0000-000000000002',
      name_uz: 'Buyurtma holatini kuzatish',
      name_ru: 'Отслеживание статуса заказа',
      name_en: 'Track Order Status',
      description_uz: 'Buyurtma holatini real vaqtda kuzatib boring',
      description_ru: 'Отслеживайте статус заказа в реальном времени',
      description_en: 'Track your order status in real-time',
      icon: '📱',
      is_active: true,
      sort: 2,
    },
    {
      id: '90000000-0000-0000-0000-000000000003',
      name_uz: 'Onlayn to\'lov',
      name_ru: 'Онлайн оплата',
      name_en: 'Online Payment',
      description_uz: 'Click, Payme va boshqa to\'lov tizimlari orqali to\'lang',
      description_ru: 'Оплачивайте через Click, Payme и другие платежные системы',
      description_en: 'Pay through Click, Payme and other payment systems',
      icon: '💳',
      is_active: true,
      sort: 3,
    },
    {
      id: '90000000-0000-0000-0000-000000000004',
      name_uz: 'Yetkazib berish',
      name_ru: 'Доставка',
      name_en: 'Delivery Service',
      description_uz: 'Telefoningizni olib ketish va qaytarish xizmati',
      description_ru: 'Услуга забора и возврата телефона',
      description_en: 'Phone pickup and return service',
      icon: '🚚',
      is_active: true,
      sort: 4,
    },
    {
      id: '90000000-0000-0000-0000-000000000005',
      name_uz: 'Ijara telefoni',
      name_ru: 'Аренда телефона',
      name_en: 'Phone Rental',
      description_uz: 'Ta\'mir davomida vaqtincha telefon ijarasi',
      description_ru: 'Аренда временного телефона на время ремонта',
      description_en: 'Temporary phone rental during repair',
      icon: '📞',
      is_active: true,
      sort: 5,
    },
    {
      id: '90000000-0000-0000-0000-000000000006',
      name_uz: 'Push bildirishnomalar',
      name_ru: 'Push уведомления',
      name_en: 'Push Notifications',
      description_uz: 'Buyurtma haqida darhol xabar oling',
      description_ru: 'Получайте мгновенные уведомления о заказе',
      description_en: 'Get instant notifications about your order',
      icon: '🔔',
      is_active: true,
      sort: 6,
    },
    {
      id: '90000000-0000-0000-0000-000000000007',
      name_uz: 'Qo\'llab-quvvatlash xizmati',
      name_ru: 'Служба поддержки',
      name_en: 'Customer Support',
      description_uz: '24/7 mijozlarni qo\'llab-quvvatlash xizmati',
      description_ru: 'Круглосуточная служба поддержки клиентов',
      description_en: '24/7 customer support service',
      icon: '💬',
      is_active: true,
      sort: 7,
    },
    {
      id: '90000000-0000-0000-0000-000000000008',
      name_uz: 'Tamir tarixi',
      name_ru: 'История ремонтов',
      name_en: 'Repair History',
      description_uz: 'Barcha ta\'mir buyurtmalaringiz tarixi',
      description_ru: 'История всех ваших заявок на ремонт',
      description_en: 'History of all your repair orders',
      icon: '📋',
      is_active: true,
      sort: 8,
    },
    {
      id: '90000000-0000-0000-0000-000000000009',
      name_uz: 'Narxlarni hisoblash',
      name_ru: 'Калькулятор цен',
      name_en: 'Price Calculator',
      description_uz: 'Ta\'mir narxini oldindan hisoblang',
      description_ru: 'Предварительно рассчитайте стоимость ремонта',
      description_en: 'Pre-calculate repair costs',
      icon: '🧮',
      is_active: true,
      sort: 9,
    },
    {
      id: '90000000-0000-0000-0000-000000000010',
      name_uz: 'Filiallarni topish',
      name_ru: 'Поиск филиалов',
      name_en: 'Find Branches',
      description_uz: 'Eng yaqin filialimizni toping',
      description_ru: 'Найдите ближайший филиал',
      description_en: 'Find the nearest branch',
      icon: '📍',
      is_active: true,
      sort: 10,
    },
    {
      id: '90000000-0000-0000-0000-000000000011',
      name_uz: 'Chegirmalar va aksiyalar',
      name_ru: 'Скидки и акции',
      name_en: 'Discounts and Promotions',
      description_uz: 'Maxsus chegirmalar va aksiyalardan foydalaning',
      description_ru: 'Воспользуйтесь специальными скидками и акциями',
      description_en: 'Take advantage of special discounts and promotions',
      icon: '🎁',
      is_active: true,
      sort: 11,
    },
    {
      id: '90000000-0000-0000-0000-000000000012',
      name_uz: 'Kafolat xizmati',
      name_ru: 'Гарантийное обслуживание',
      name_en: 'Warranty Service',
      description_uz: 'Ta\'mir ishlari uchun kafolat berish',
      description_ru: 'Гарантия на ремонтные работы',
      description_en: 'Warranty on repair services',
      icon: '🛡️',
      is_active: true,
      sort: 12,
    },
  ];

  for (const feature of appFeatures) {
    await knex('app_features').insert({
      id: feature.id,
      name_uz: feature.name_uz,
      name_ru: feature.name_ru,
      name_en: feature.name_en,
      description_uz: feature.description_uz,
      description_ru: feature.description_ru,
      description_en: feature.description_en,
      icon: feature.icon,
      is_active: feature.is_active,
      sort: feature.sort,
      status: 'Open',
      created_by: '00000000-0000-0000-0000-000000000001', // Super admin
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    });
  }
};