const { v4: uuidv4 } = require('uuid');

exports.seed = async function (knex) {
  await knex('rental_phone_devices').del();

  const rentalPhones = [
    {
      id: uuidv4(),
      name: 'iPhone 11 (64GB, Black)',
      brand: 'Apple',
      model: 'iPhone 11',
      imei: '358123456789012',
      color: 'Black',
      storage_capacity: '64GB',
      battery_capacity: '85%',
      is_free: false,
      daily_rent_price: 35000.00,
      deposit_amount: 1000000.00,
      currency: 'UZS',
      is_available: true,
      status: 'Available',
      condition: 'Good',
      quantity: 1,
      quantity_available: 1,
      notes: 'Minor scratches on the back',
      sort: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: uuidv4(),
      name: 'Samsung Galaxy A53 (128GB, Blue)',
      brand: 'Samsung',
      model: 'Galaxy A53',
      imei: '354987654321098',
      color: 'Blue',
      storage_capacity: '128GB',
      battery_capacity: '92%',
      is_free: true,
      daily_rent_price: 0.00,
      deposit_amount: 1500000.00,
      currency: 'UZS',
      is_available: true,
      status: 'Available',
      condition: 'Excellent',
      quantity: 1,
      quantity_available: 1,
      notes: 'Perfect condition',
      sort: 2,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: uuidv4(),
      name: 'Redmi Note 12 (128GB, Gray)',
      brand: 'Xiaomi',
      model: 'Redmi Note 12',
      imei: '868111122223333',
      color: 'Gray',
      storage_capacity: '128GB',
      battery_capacity: '100%',
      is_free: false,
      daily_rent_price: 25000.00,
      deposit_amount: 800000.00,
      currency: 'UZS',
      is_available: false,
      status: 'Rented',
      condition: 'Excellent',
      quantity: 1,
      quantity_available: 0,
      notes: 'Brand new screen',
      sort: 3,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: uuidv4(),
      name: 'iPhone 13 Pro (256GB, Sierra Blue)',
      brand: 'Apple',
      model: 'iPhone 13 Pro',
      imei: '359333344445555',
      color: 'Sierra Blue',
      storage_capacity: '256GB',
      battery_capacity: '88%',
      is_free: false,
      daily_rent_price: 60000.00,
      deposit_amount: 3000000.00,
      currency: 'UZS',
      is_available: true,
      status: 'Available',
      condition: 'Good',
      quantity: 1,
      quantity_available: 1,
      notes: 'No case included',
      sort: 4,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    }
  ];

  await knex('rental_phone_devices').insert(rentalPhones);
};
