// utils/permission.util.ts
export function extractStatusPermissionFields(row: Record<string, any>) {
    const {
        can_add,
        can_view,
        can_update,
        can_delete,
        can_payment_add,
        can_payment_cancel,
        can_assign_admin,
        can_notification,
        can_notification_bot,
        can_change_active,
        can_change_status,
        can_view_initial_problems,
        can_change_initial_problems,
        can_view_final_problems,
        can_change_final_problems,
        can_comment,
        can_pickup_manage,
        can_delivery_manage,
        can_view_payments,
        can_view_history,
    } = row;

    return {
        can_add,
        can_view,
        can_update,
        can_delete,
        can_payment_add,
        can_payment_cancel,
        can_assign_admin,
        can_notification,
        can_notification_bot,
        can_change_active,
        can_change_status,
        can_view_initial_problems,
        can_change_initial_problems,
        can_view_final_problems,
        can_change_final_problems,
        can_comment,
        can_pickup_manage,
        can_delivery_manage,
        can_view_payments,
        can_view_history,
    };
}
